### ISSUE TITLE
Nuxt Universal Mode: window is not defined error

### ISSUE THREAD

**Issue by alwindeleon** [f-elix/vue-xstate-plugin#1]
Good day! I'm currently having the error above when I use this with Nuxt in universal mode. I think we should add a not in the readme about making sure the plugin only works in the client side.

Either you add .client in the filename of the plugin or you add a property in the nuxt.config file. Let me know what you think and I'd definitely submit a PR if you think this is okay.

Thanks a ton for this library!!

**Comment by f-elix** [comment]
Hey! 

Sorry for not answering earlier.
Go ahead and submit the pull request, I'll merge it.

Thanks so much for contributing!

**Comment by alwindeleon** [comment]
Here is the small PR 🚀  Let me know what you think 👍 
#2
